#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-worker-update-community-apps-themes-downloads"
main = "src/index.js"
compatibility_date = "2024-07-18"
workers_dev = false

[triggers]
crons = ["0 0 * * *"]
